<?="<?php\n"?>
declare(strict_types=1);

namespace <?=$data['namespace']?>\Controller\Adminhtml\<?=$data['entity_class_name']?>;

use <?=$data['namespace']?>\Api\<?=$data['entity_class_name']?>RepositoryInterface;
use <?=$data['namespace']?>\Api\Data\<?=$data['entity_class_name']?>Interface;
use Magento\Backend\App\Action;
use Magento\Backend\App\Action\Context;
use Magento\Framework\Controller\ResultInterface;
use Magento\Framework\Exception\CouldNotDeleteException;
use Magento\Framework\Exception\NoSuchEntityException;

/**
 * @author naydav <valeriy.nayda@gmail.com>
 */
class Delete extends Action
{
    /**
     * @see _isAllowed()
     */
    const ADMIN_RESOURCE = '<?=$data['acl_resource']?>::<?=$data['entity_acl_resource']?>';

    /**
     * @var <?=$data['entity_class_name']?>RepositoryInterface
     */
    private $<?=lcfirst($data['entity_class_name'])?>Repository;

    /**
     * @param Context $context
     * @param <?=$data['entity_class_name']?>RepositoryInterface $<?=lcfirst($data['entity_class_name'])?>Repository
     */
    public function __construct(
        Context $context,
        <?=$data['entity_class_name']?>RepositoryInterface $<?=lcfirst($data['entity_class_name'])?>Repository
    ) {
        parent::__construct($context);
        $this-><?=lcfirst($data['entity_class_name'])?>Repository = $<?=lcfirst($data['entity_class_name'])?>Repository;
    }

    /**
     * @inheritdoc
     */
    public function execute(): ResultInterface
    {
        $resultRedirect = $this->resultRedirectFactory->create();

        $<?=$data['entity_camelcase_id_field']?> = $this->getRequest()->getPost(<?=$data['entity_class_name']?>Interface::<?=strtoupper($data['entity_id_field'])?>);
        if (null === $<?=$data['entity_camelcase_id_field']?>) {
            $this->messageManager->addErrorMessage(__('Wrong request.'));
            return $resultRedirect->setPath('*/*');
        }

        try {
            $<?=$data['entity_camelcase_id_field']?> = (int)$<?=$data['entity_camelcase_id_field']?>;
            $this-><?=lcfirst($data['entity_class_name'])?>Repository->deleteById($<?=$data['entity_camelcase_id_field']?>);
            $this->messageManager->addSuccessMessage(__('The <?=$data['entity_display_name']?> has been deleted.'));
            $resultRedirect->setPath('*/*');
        } catch (NoSuchEntityException $e) {
            $this->messageManager->addErrorMessage(
                __('<?=$data['entity_display_name']?> with id "%id" does not exist.', ['id' => $<?=$data['entity_camelcase_id_field']?>])
            );
            $resultRedirect->setPath('*/*');
        } catch (CouldNotDeleteException $e) {
            $this->messageManager->addErrorMessage($e->getMessage());
            $resultRedirect->setPath('*/*/edit', [
            <?=$data['entity_class_name']?>Interface::<?=strtoupper($data['entity_id_field'])?> => $<?=$data['entity_camelcase_id_field']?>,
                '_current' => true,
            ]);
        }
        return $resultRedirect;
    }
}
