<?="<?php\n"?>
declare(strict_types=1);

namespace <?=$data['namespace']?>\Controller\Adminhtml\<?=$data['entity_class_name']?>;

use Magento\Backend\App\Action;
use Magento\Backend\Model\View\Result\Page;
use Magento\Framework\Controller\ResultFactory;
use Magento\Framework\Controller\ResultInterface;

/**
 * @author naydav <valeriy.nayda@gmail.com>
 */
class NewAction extends Action
{
    /**
     * @see _isAllowed()
     */
    const ADMIN_RESOURCE = '<?=$data['acl_resource']?>::<?=$data['entity_acl_resource']?>';

    /**
     * @inheritdoc
     */
    public function execute(): ResultInterface
    {
        /** @var Page $resultPage */
        $resultPage = $this->resultFactory->create(ResultFactory::TYPE_PAGE);
        $resultPage->setActiveMenu('<?=$data['acl_resource']?>::<?=$data['entity_acl_resource']?>');
        $resultPage->getConfig()->getTitle()->prepend(__('New <?=$data['entity_display_name']?>'));
        return $resultPage;
    }
}
