<?="<?php\n"?>
declare(strict_types=1);

namespace <?=$data['namespace']?>\Model\<?=$data['entity_class_name']?>;

use <?=$data['namespace']?>\Api\Data\<?=$data['entity_class_name']?>SearchResultInterface;
use Magento\Framework\Api\SearchCriteriaInterface;

/**
 * Find <?=$data['entities_display_name']?> by SearchCriteria command (Service Provider Interface - SPI)
 *
 * Separate command interface to which Repository proxies initial GetList call, could be considered as SPI - Interfaces
 * that you should extend and implement to customize current behaviour, but NOT expected to be used (called) in the code
 * of business logic directly
 *
 * @see \<?=$data['namespace']?>\Api\<?=$data['entity_class_name']?>RepositoryInterface
 * @api
 */
interface Get<?=$data['entity_class_name']?>ListInterface
{
    /**
     * Find <?=$data['entities_display_name']?> by given SearchCriteria
     *
     * @param SearchCriteriaInterface $searchCriteria
     * @return <?=$data['entity_class_name']?>SearchResultInterface
     */
    public function execute(SearchCriteriaInterface $searchCriteria): <?=$data['entity_class_name']?>SearchResultInterface;
}
