<?="<?php\n"?>
declare(strict_types=1);

namespace <?=$data['namespace']?>\Api;

use Magento\Framework\Api\SearchCriteriaInterface;
use <?=$data['namespace']?>\Api\Data\<?=$data['entity_class_name']?>Interface;
use <?=$data['namespace']?>\Api\Data\<?=$data['entity_class_name']?>SearchResultInterface;

/**
 * In Magento 2 Repository considered as an implementation of Facade pattern which provides a simplified interface
 * to a larger body of code responsible for Domain Entity management
 *
 * The main intention is to make API more readable and reduce dependencies of business logic code on the inner workings
 * of a module, since most code uses the facade, thus allowing more flexibility in developing the system
 *
 * Along with this such approach helps to segregate two responsibilities:
 * 1. Repository now could be considered as an API - Interface for usage (calling) in the business logic
 * 2. Separate class-commands to which Repository proxies initial call (like, Get Save GetList Delete) could be
 *    considered as SPI - Interfaces that you should extend and implement to customize current behaviour
 *
 * Used fully qualified namespaces in annotations for proper work of WebApi request parser
 *
 * @api
 * @author naydav <valeriy.nayda@gmail.com>
 */
interface <?=$data['entity_class_name']?>RepositoryInterface
{
    /**
     * Save <?=$data['entity_class_name']?> data
     *
     * @param \<?=$data['namespace']?>\Api\Data\<?=$data['entity_class_name']?>Interface $<?=lcfirst($data['entity_class_name'])?><?="\n"?>
     * @return int
     * @throws \Magento\Framework\Validation\ValidationException
     * @throws \Magento\Framework\Exception\CouldNotSaveException
     */
    public function save(<?=$data['entity_class_name']?>Interface $<?=lcfirst($data['entity_class_name'])?>): int;

    /**
     * Get <?=$data['entity_class_name']?> data by given identifier
     *
     * If you want to create plugin on get method, also you need to create separate
     * plugin on getList method, because entity loading way is different for these methods
     *
     * @param int $<?=$data['entity_camelcase_id_field']?><?="\n"?>
     * @return \<?=$data['namespace']?>\Api\Data\<?=$data['entity_class_name']?>Interface
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    public function get(int $<?=$data['entity_camelcase_id_field']?>): <?=$data['entity_class_name']?>Interface;

    /**
     * Find <?=$data['entities_display_name']?> by given SearchCriteria
     *
     * @param \Magento\Framework\Api\SearchCriteriaInterface $searchCriteria
     * @return \<?=$data['namespace']?>\Api\Data\<?=$data['entity_class_name']?>SearchResultInterface
     */
    public function getList(SearchCriteriaInterface $searchCriteria): <?=$data['entity_class_name']?>SearchResultInterface;

    /**
     * Delete the <?=$data['entity_class_name']?> data by identifier. If <?=$data['entity_class_name']?> is not found do nothing
     *
     * @param int $<?=$data['entity_camelcase_id_field']?><?="\n"?>
     * @return void
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     * @throws \Magento\Framework\Exception\CouldNotDeleteException
     */
    public function deleteById(int $<?=$data['entity_camelcase_id_field']?>);
}
