<?="<?php\n"?>
namespace <?=$data['namespace']?>\Test\Integration\Backend;

use Engine\Test\Backend\AssertMenuItem;
use Magento\TestFramework\TestCase\AbstractBackendController;

/**
 * @author naydav <valeriy.nayda@gmail.com>
 * @magentoAppArea adminhtml
 */
class MenuTest extends AbstractBackendController
{
    /**
     * Request uri
     */
    const REQUEST_URI = 'backend/backend';

    public function testMenu()
    {
        $this->dispatch(self::REQUEST_URI);
        $body = $this->getResponse()->getBody();

        self::assertNotEmpty($body);

        AssertMenuItem::assert(
            $body,
            '<?=str_replace('_', '-', strtolower($data['module'] . '-' . $data['name']))?>',
            '<?=$data['display_name']?>'
        );
<?php foreach ($data['entities'] as $key => $entityData): ?>

        AssertMenuItem::assert(
            $body,
            '<?=str_replace('_', '-', strtolower($data['module'] . '-' . $entityData['entity_name']))?>-index',
            '<?=$entityData['entity_display_name']?> List',
            '<?=$data['route_front_name']?>/<?=lcfirst($entityData['entity_class_name'])?>'
        );
        AssertMenuItem::assert(
            $body,
            '<?=str_replace('_', '-', strtolower($data['module'] . '-' . $entityData['entity_name']))?>-new',
            'Add <?=$entityData['entity_display_name']?>',
            '<?=$data['route_front_name']?>/<?=lcfirst($entityData['entity_class_name'])?>/new'
        );
<?php endforeach; ?>
    }
}
