<?="<?php\n"?>
declare(strict_types=1);

namespace <?=$data['namespace']?>\Test\Integration\Controller\Adminhtml\<?=$data['entity_class_name']?>;

use Engine\Test\Backend\AssertAddButton;
use Engine\Test\Backend\AssertListing;
use Engine\Test\AssertPageHeader;
use Engine\Test\AssertPageTitle;
use Magento\Framework\Message\MessageInterface;
use Magento\TestFramework\TestCase\AbstractBackendController;
use Zend\Http\Response;

/**
 * @author naydav <valeriy.nayda@gmail.com>
 * @magentoAppArea adminhtml
 */
class IndexTest extends AbstractBackendController
{
    public function testExecute()
    {
        $this->dispatch('backend/<?=$data['route_front_name']?>/<?=lcfirst($data['entity_class_name'])?>');
        self::assertEquals(Response::STATUS_CODE_200, $this->getResponse()->getStatusCode());
        $this->assertSessionMessages($this->isEmpty(), MessageInterface::TYPE_ERROR);

        $body = $this->getResponse()->getBody();
        self::assertNotEmpty($body);

        AssertPageTitle::assert($body, __('Manage <?=$data['entities_display_name']?>'));
        AssertPageHeader::assert($body, __('Manage <?=$data['entities_display_name']?>'));
        AssertAddButton::assert($body, 'add-button');
        AssertListing::assert($body, '<?=$data['entity_ui_name']?>_listing');
    }
}
