<?="<?php\n"?>
declare(strict_types=1);

namespace <?=$data['namespace']?>\Test\Integration\Controller\Adminhtml\<?=$data['entity_class_name']?>;

use <?=$data['namespace']?>\Api\<?=$data['entity_class_name']?>RepositoryInterface;
use Magento\Framework\Api\SearchCriteriaBuilder;
use Magento\Framework\Api\SearchCriteriaBuilderFactory;
use Magento\Framework\Data\Form\FormKey;
use Magento\Framework\Message\MessageInterface;
use Magento\TestFramework\TestCase\AbstractBackendController;
use Zend\Http\Request;
use Zend\Http\Response;

/**
 * @author naydav <valeriy.nayda@gmail.com>
 * @magentoAppArea adminhtml
 */
class MassDeleteTest extends AbstractBackendController
{
    /**
     * Request uri
     */
    const REQUEST_URI = 'backend/<?=$data['route_front_name']?>/<?=lcfirst($data['entity_class_name'])?>/massDelete';

    /**
     * @var FormKey
     */
    private $formKey;

    /**
     * @var <?=$data['entity_class_name']?>RepositoryInterface
     */
    private $<?=lcfirst($data['entity_class_name'])?>Repository;

    /**
     * @var SearchCriteriaBuilderFactory
     */
    private $searchCriteriaBuilderFactory;

    public function setUp()
    {
        parent::setUp();
        $this->formKey = $this->_objectManager->get(FormKey::class);
        $this-><?=lcfirst($data['entity_class_name'])?>Repository = $this->_objectManager->get(
            <?=$data['entity_class_name']?>RepositoryInterface::class
        );
        $this->searchCriteriaBuilderFactory = $this->_objectManager->get(SearchCriteriaBuilderFactory::class);
    }

    /**
     * @magentoDataFixture ../../../../app/code/<?=$data['namespace_prefix']?>/<?=$data['name_camelcase']?>/Test/_files/<?=$data['entities_name']?>.php
     */
    public function testMassDelete()
    {
        $initial<?=ucfirst($data['entities_name_camelcase'])?>Count = $this->get<?=ucfirst($data['entities_name_camelcase'])?>Count();
        $request = $this->getRequest();
        $request->setMethod(Request::METHOD_POST);
        $request->setPostValue([
            'form_key' => $this->formKey->getFormKey(),
            'selected' => [
                100,
                200,
                400,
            ],
            'namespace' => '<?=$data['entity_ui_name']?>_listing',
        ]);

        $this->dispatch(self::REQUEST_URI);

        self::assertEquals(Response::STATUS_CODE_302, $this->getResponse()->getStatusCode());
        $this->assertRedirect($this->stringContains('backend/<?=$data['route_front_name']?>/<?=lcfirst($data['entity_class_name'])?>'));
        $this->assertSessionMessages($this->isEmpty(), MessageInterface::TYPE_ERROR);
        $this->assertSessionMessages(
            $this->contains('You deleted 3 <?=$data['entity_display_name']?>(s).'),
            MessageInterface::TYPE_SUCCESS
        );
        self::assertEquals(($initial<?=ucfirst($data['entities_name_camelcase'])?>Count - 3), $this->get<?=ucfirst($data['entities_name_camelcase'])?>Count());
    }

    /**
     * @magentoDataFixture ../../../../app/code/<?=$data['namespace_prefix']?>/<?=$data['name_camelcase']?>/Test/_files/<?=$data['entities_name']?>.php
     */
    public function testMassDeleteWithWrongRequestMethod()
    {
        $initial<?=ucfirst($data['entities_name_camelcase'])?>Count = $this->get<?=ucfirst($data['entities_name_camelcase'])?>Count();
        $request = $this->getRequest();
        $request->setMethod(Request::METHOD_GET);
        $request->setQueryValue([
            'form_key' => $this->formKey->getFormKey(),
            'selected' => [
                100,
                200,
                400,
            ],
            'namespace' => '<?=$data['entity_ui_name']?>_listing',
        ]);

        $this->dispatch(self::REQUEST_URI);

        self::assertEquals(Response::STATUS_CODE_302, $this->getResponse()->getStatusCode());
        $this->assertRedirect($this->stringContains('backend/<?=$data['route_front_name']?>/<?=lcfirst($data['entity_class_name'])?>'));
        $this->assertSessionMessages($this->contains('Wrong request.'), MessageInterface::TYPE_ERROR);
        self::assertEquals($initial<?=ucfirst($data['entities_name_camelcase'])?>Count, $this->get<?=ucfirst($data['entities_name_camelcase'])?>Count());
    }

    /**
     * @magentoDataFixture ../../../../app/code/<?=$data['namespace_prefix']?>/<?=$data['name_camelcase']?>/Test/_files/<?=$data['entities_name']?>.php
     */
    public function testMassDeleteWithNotExistEntityId()
    {
        $initial<?=ucfirst($data['entities_name_camelcase'])?>Count = $this->get<?=ucfirst($data['entities_name_camelcase'])?>Count();
        $request = $this->getRequest();
        $request->setMethod(Request::METHOD_POST);
        $request->setPostValue([
            'form_key' => $this->formKey->getFormKey(),
            'selected' => [
                100,
                -1,
                400,
            ],
            'namespace' => '<?=$data['entity_ui_name']?>_listing',
        ]);

        $this->dispatch(self::REQUEST_URI);

        self::assertEquals(Response::STATUS_CODE_302, $this->getResponse()->getStatusCode());
        $this->assertRedirect($this->stringContains('backend/<?=$data['route_front_name']?>/<?=lcfirst($data['entity_class_name'])?>'));
        $this->assertSessionMessages($this->isEmpty(), MessageInterface::TYPE_ERROR);
        $this->assertSessionMessages(
            $this->contains('You deleted 2 <?=$data['entity_display_name']?>(s).'),
            MessageInterface::TYPE_SUCCESS
        );
        self::assertEquals(($initial<?=ucfirst($data['entities_name_camelcase'])?>Count - 2), $this->get<?=ucfirst($data['entities_name_camelcase'])?>Count());
    }

    /**
     * @return int
     */
    private function get<?=ucfirst($data['entities_name_camelcase'])?>Count(): int
    {
        /** @var SearchCriteriaBuilder $searchCriteriaBuilder */
        $searchCriteriaBuilder = $this->searchCriteriaBuilderFactory->create();
        $searchCriteria = $searchCriteriaBuilder->create();

        $result = $this-><?=lcfirst($data['entity_class_name'])?>Repository->getList($searchCriteria);
        return $result->getTotalCount();
    }
}
