<?="<?php\n"?>
declare(strict_types=1);

namespace <?=$data['namespace']?>\Api\Data;

use Magento\Framework\Api\SearchResultsInterface;

/**
 * Search results of Repository::getList method
 *
 * Used fully qualified namespaces in annotations for proper work of WebApi request parser
 *
 * @api
 * @author naydav <valeriy.nayda@gmail.com>
 */
interface <?=$data['entity_class_name']?>SearchResultInterface extends SearchResultsInterface
{
    /**
     * @return \<?=$data['namespace']?>\Api\Data\<?=$data['entity_class_name']?>Interface[]
     */
    public function getItems();

    /**
     * @param \<?=$data['namespace']?>\Api\Data\<?=$data['entity_class_name']?>Interface[] $items
     * @return void
     */
    public function setItems(array $items);
}
