<?="<?php\n"?>
declare(strict_types=1);

namespace <?=$data['namespace']?>\Model\<?=$data['entity_class_name']?>\Validator;

use <?=$data['namespace']?>\Api\Data\<?=$data['entity_class_name']?>Interface;
use Magento\Framework\Validation\ValidationResult;
use Magento\Framework\Validation\ValidationResultFactory;

/**
 * Check that name is valid
 *
 * @author naydav <valeriy.nayda@gmail.com>
 */
class NameValidator implements <?=$data['entity_class_name']?>ValidatorInterface
{
    /**
     * @var ValidationResultFactory
     */
    private $validationResultFactory;

    /**
     * @param ValidationResultFactory $validationResultFactory
     */
    public function __construct(ValidationResultFactory $validationResultFactory)
    {
        $this->validationResultFactory = $validationResultFactory;
    }

    /**
     * @inheritdoc
     */
    public function validate(<?=$data['entity_class_name']?>Interface $<?=lcfirst($data['entity_class_name'])?>): ValidationResult
    {
        $value = (string)$<?=lcfirst($data['entity_class_name'])?>->getName();

        if ('' === trim($value)) {
            $errors[] = __('"%field" can not be empty.', ['field' => <?=$data['entity_class_name']?>Interface::NAME]);
        } else {
            $errors = [];
        }
        return $this->validationResultFactory->create(['errors' => $errors]);
    }
}
